apiVersion: v1
kind: ConfigMap
metadata:
  name: env-configmap
data:
  target_url: "{{.Values.env.target_url}}"
  port: "{{.Values.env.port}}"
  well_known_url: "{{.Values.env.well_known_url}}"
  client_id: "{{.Values.env.client_id}}"
  redirect_uri: "{{.Values.env.redirect_uri}}"
  audience: "{{.Values.env.audience}}"
  scopes: "{{.Values.env.scopes}}"
  session_key: "{{.Values.env.session_key}}"
  logLevel: "{{.Values.env.logLevel}}"