apiVersion: v1
kind: Pod
metadata:
  name: side-sample
  labels:
    app: side-sample
spec:
  containers:
  - name: sample-container
    image: aminrbizid/sample:1.0
    ports:
    - containerPort: 5080
  - name: sidecar-container
    image: {{.Values.image}}
    ports:
    - containerPort: {{.Values.env.port}}
    envFrom:
    - configMapRef:
        name: env-configmap

